param(
    [ValidateSet('Api','Browser')][string]$Suite = 'Api',
    [string]$Instance = '.\SQLEXPRESS',
    [int]$Port = 1433
)
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
$suffix = [Guid]::NewGuid().ToString('N').Substring(0,12)
$database = "SkyTraceTest_$suffix"
$login = "skytrace_test_$suffix"
$password = 'St!' + [Guid]::NewGuid().ToString('N')
$connection = New-Object System.Data.SqlClient.SqlConnection("Server=$Instance;Database=master;Integrated Security=True;TrustServerCertificate=True")
$createdDb = $false
$createdLogin = $false
$environmentNames = @('SPRING_DATASOURCE_URL','E2E_DB_URL','SPRING_DATASOURCE_USERNAME',
    'SPRING_DATASOURCE_PASSWORD','SPRING_DATASOURCE_DRIVER_CLASS_NAME','PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD',
    'E2E_BASE_URL','E2E_ADMIN_PASSWORD')
$savedEnvironment = @{}
foreach ($name in $environmentNames) { $savedEnvironment[$name] = [Environment]::GetEnvironmentVariable($name, 'Process') }
function Execute-Sql([string]$sql) {
    $command = $connection.CreateCommand()
    $command.CommandText = $sql
    [void]$command.ExecuteNonQuery()
    $command.Dispose()
}
try {
    $connection.Open()
    Execute-Sql "CREATE DATABASE [$database]"
    $createdDb = $true
    Execute-Sql "CREATE LOGIN [$login] WITH PASSWORD=N'$password', CHECK_POLICY=OFF"
    $createdLogin = $true
    Execute-Sql "USE [$database]; CREATE USER [$login] FOR LOGIN [$login] WITH DEFAULT_SCHEMA=dbo; ALTER ROLE db_datareader ADD MEMBER [$login]; ALTER ROLE db_datawriter ADD MEMBER [$login]; ALTER ROLE db_ddladmin ADD MEMBER [$login]; USE master;"
    $env:SPRING_DATASOURCE_URL = "jdbc:sqlserver://localhost:$Port;databaseName=$database;encrypt=false;trustServerCertificate=true"
    $env:E2E_DB_URL = $env:SPRING_DATASOURCE_URL
    $env:SPRING_DATASOURCE_USERNAME = $login
    $env:SPRING_DATASOURCE_PASSWORD = $password
    $env:SPRING_DATASOURCE_DRIVER_CLASS_NAME = 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    $env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = '1'
    [Environment]::SetEnvironmentVariable('E2E_BASE_URL', $null, 'Process')
    [Environment]::SetEnvironmentVariable('E2E_ADMIN_PASSWORD', $null, 'Process')
    Push-Location (Join-Path $repo 'app')
    try {
        if ($Suite -eq 'Browser') { & .\mvnw.cmd -B -ntp -Pe2e '-Dtest=BrowserE2ETest' test }
        else { & .\mvnw.cmd -B -ntp '-Dtest=ApiIntegrationTest' test }
        $testExit = $LASTEXITCODE
    } finally { Pop-Location }
    if ($testExit -ne 0) { throw "SQL Server $Suite tests failed ($testExit)" }
} finally {
    foreach ($name in $environmentNames) { [Environment]::SetEnvironmentVariable($name, $savedEnvironment[$name], 'Process') }
    # Only identifiers generated by this invocation may be removed.
    if ($database -notmatch '^SkyTraceTest_[a-f0-9]{12}$' -or $login -notmatch '^skytrace_test_[a-f0-9]{12}$') {
        throw 'Unexpected cleanup target'
    }
    if ($connection.State -eq 'Open') {
        if ($createdDb) { Execute-Sql "ALTER DATABASE [$database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$database];" }
        if ($createdLogin) { Execute-Sql "DROP LOGIN [$login];" }
        $connection.Close()
    }
    $connection.Dispose()
}
